name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build Image and Push to GCR
      env:
        TAG: '0.1'
      run: |
        docker build -t ng-covid:$TAG .
        docker tag ng-covid:$TAG zeelz/ng-covid19:$TAG
        docker tag ng-covid:$TAG gcr.io/civil-forge-282605/ng-covid:$TAG
        cat gcr-sa-key.json | docker login -u _json_key --password-stdin https://gcr.io
        docker push gcr.io/civil-forge-282605/ng-covid:$TAG