name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        docker build -t ng-covid:0.3 .
        docker tag ng-covid:0.3 zeelz/ng-covid19:0.3
        docker login -u zeelz -p bb56003f-4a9a-40fc-91be-774d937775af
        docker push zeelz/ng-covid19:0.3
