name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      env:
        DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        TAG: '0.4'
      run: |
        docker build -t ng-covid:$TAG .
        docker tag ng-covid:$TAG zeelz/ng-covid19:$TAG
        docker login -u zeelz -p $DOCKER_TOKEN
        docker push zeelz/ng-covid19:$TAG
