name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and Push Docker image
      env:
        DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        TAG: '0.4'
      run: |
        cat gcr-sa-key.json | docker login -u _json_key --password-stdin https://gcr.io
